import { Pizza } from './types';

export const PIZZAS: Pizza[] = [
  {
    id: 'diavola',
    name: 'THE DEVIL',
    displayName: 'Pepperoni Supreme',
    tagline: 'WOOD-FIRED SPICED CHARCUTERIE',
    description: 'Double-cured Calabrian salami, artisanal black truffle olives, hand-torn whole-milk mozzarella, and charred red chilis over our signature 48-hour slow-fermented Neapolitan sourdough base.',
    price: 24.50,
    rating: 4.9,
    reviewsCount: 382,
    prepTime: '12 min',
    calories: 840,
    imageUrl: '/pizza-supreme.png',
    bgSymbol: 'DEVIL',
    accentColor: '#8E1F0D',
    mainColor: '#C64A19',
    bgLightColor: '#FFECDA',
    ingredients: ['onion', 'olive', 'tomato', 'basil']
  },
  {
    id: 'margherita',
    name: 'SPRING',
    displayName: 'Margherita Delight',
    tagline: 'CONCENTRATION OF ITALIAN SUNSHINE',
    description: 'Sweet San Marzano gold tomatoes, premium buffalo mozzarella, aromatic pressed olive oil, and freshly picked organic Genovese basil leaves baked until blistering.',
    price: 19.50,
    rating: 4.8,
    reviewsCount: 512,
    prepTime: '10 min',
    calories: 720,
    imageUrl: '/pizza-main.png',
    bgSymbol: 'SPRING',
    accentColor: '#C64A19',
    mainColor: '#8E1F0D',
    bgLightColor: '#FFF2E5',
    ingredients: ['basil', 'tomato', 'onion']
  },
  {
    id: 'ortolana',
    name: 'GARDEN',
    displayName: 'Farmhouse Garden',
    tagline: 'PREMIUM FLOURISHING HARVEST',
    description: 'Wood-roasted cremini mushrooms, crisp organic jalapeños, sweet gold cherry tomatoes, red onion strings, and fresh mountain oregano, paired with an herb-infused extra virgin olive oil crust drizzle.',
    price: 22.00,
    rating: 4.9,
    reviewsCount: 224,
    prepTime: '11 min',
    calories: 780,
    imageUrl: '/pizza-supreme.png',
    bgSymbol: 'GARDEN',
    accentColor: '#4A5D4E',
    mainColor: '#8E1F0D',
    bgLightColor: '#F0EAD6',
    ingredients: ['mushroom', 'jalapeno', 'onion', 'tomato', 'basil']
  },
  {
    id: 'bianca',
    name: 'WHITE SNOW',
    displayName: 'Garlic Parmesan',
    tagline: 'CREAMY GARLIC INFUSION',
    description: 'Rich garlic parmesan cream sauce, fresh mozzarella, roasted garlic cloves, and a hint of black pepper on our classic sourdough base.',
    price: 21.00,
    rating: 4.7,
    reviewsCount: 180,
    prepTime: '10 min',
    calories: 750,
    imageUrl: '/pizza-main.png',
    bgSymbol: 'WHITE',
    accentColor: '#B0A88D',
    mainColor: '#8E1F0D',
    bgLightColor: '#F9F6F0',
    ingredients: ['mushroom', 'onion', 'basil']
  },
  {
    id: 'carne',
    name: 'MEAT LOVER',
    displayName: 'Carnivore Feast',
    tagline: 'HEARTY MEAT SELECTION',
    description: 'A robust blend of Italian sausage, pepperoni, smoked bacon, and ground beef with our rich tomato sauce and melted mozzarella.',
    price: 26.00,
    rating: 4.9,
    reviewsCount: 420,
    prepTime: '14 min',
    calories: 950,
    imageUrl: '/pizza-supreme.png',
    bgSymbol: 'FEAST',
    accentColor: '#6A1B0B',
    mainColor: '#8E1F0D',
    bgLightColor: '#F5E1DA',
    ingredients: ['tomato', 'onion', 'jalapeno']
  },
  {
    id: 'pesto',
    name: 'GREEN PESTO',
    displayName: 'Pesto Chicken',
    tagline: 'HERB INFUSED CHICKEN',
    description: 'Grilled chicken breast, sun-dried tomatoes, and fresh spinach over a vibrant basil pesto sauce and mozzarella cheese.',
    price: 23.50,
    rating: 4.8,
    reviewsCount: 290,
    prepTime: '12 min',
    calories: 810,
    imageUrl: '/pizza-main.png',
    bgSymbol: 'GREEN',
    accentColor: '#3A5A38',
    mainColor: '#8E1F0D',
    bgLightColor: '#E8F0E6',
    ingredients: ['basil', 'tomato', 'mushroom']
  }
];
